version: "3"

services:
  db:
    image: "mysql:8"
    ports:
      - "127.0.0.1:23306:3306"
    environment:
      MYSQL_DATABASE: "go_nextjs_authentication"
      MYSQL_USER: "go_nextjs_authentication_user"
      MYSQL_PASSWORD: "832hf8asdf28"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

