name: Check Bundle Diff

on: [ push ]

jobs:
  master-bundle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Use Node.js v16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: | 
          yarn
          yarn build
      - run: mv artifacts/webpack-stats.json artifacts/webpack-stats-base.json
      - uses: actions/upload-artifact@v2
        with:
          name: stats
          path: frontend/artifacts/webpack-stats-base.json

  current-branch-bundle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: |
          yarn
          yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: stats
          path: frontend/artifacts/webpack-stats.json

  check-diff:
    runs-on: ubuntu-latest
    needs: [master-bundle, current-branch-bundle]
    steps:
      - name: Use Node.js v16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm install -g webpack-bundle-diff
      - uses: actions/download-artifact@v2
        with:
          name: stats
      - run: wbd diff webpack-stats.json webpack-stats-base.json -o output.json
      - run: cat output.json
